/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.sql.*;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.database;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import pengembalian.pengembalianTableModel;

/**
 *
 * @author ASUS
 */
public class formKembali extends javax.swing.JInternalFrame {
    database db = new database();
    pengembalianTableModel tabelPengembalian = new pengembalianTableModel();
    /**
     * Creates new form form_kembali2
     */
    public formKembali() {
        initComponents();
        tampilData();
    }
    public void tampilData(){
        tabelPengembalian.setData(db.tampilPengembalian());
        tbKembali.setModel(tabelPengembalian);
    }
    public void refreshData(){
        tabelPengembalian.setData(db.tampilPengembalian());
        tabelPengembalian.fireTableDataChanged();
        tbKembali.changeSelection(0, 0, false, false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbKembali = new javax.swing.JTable();
        tblTambah = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        tbKembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Pinjam", "NIS", "Nama Siswa", "Tgl Pinjam", "Tgl Kembali", "Denda", "ID Pegawai"
            }
        ));
        jScrollPane1.setViewportView(tbKembali);

        tblTambah.setText("Tambah");
        tblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblTambahActionPerformed(evt);
            }
        });

        tblHapus.setText("Hapus");
        tblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblHapusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tabel Pengembalian");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cari");

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak Laporan");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(tblTambah)
                        .addGap(31, 31, 31)
                        .addComponent(tblHapus)
                        .addGap(35, 35, 35)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCetak)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tblTambah)
                    .addComponent(tblHapus)
                    .addComponent(btnRefresh)
                    .addComponent(btnCetak))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblTambahActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        formTambahKembali formTambah;
        formTambah = new formTambahKembali(frame,true);
        formTambah.setLocationRelativeTo(null);
        formTambah.setVisible(true);
        refreshData();
    }//GEN-LAST:event_tblTambahActionPerformed

    private void tblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblHapusActionPerformed
        // TODO add your handling code here:
        try{
            int baris = tbKembali.getSelectedRow();
            String no = (String) tabelPengembalian.getValueAt(baris, 0);
            String ns = (String) tabelPengembalian.getValueAt(baris, 2);
            Object[] pilihan = {"Ya","Tidak"};
            int jawaban = JOptionPane.showOptionDialog(rootPane,
                "Apakah yakin menghapus data peminjaman dengan nomor "+no+""
                + " atas nama "+ns+"?",
                "Konfirmasi",JOptionPane.DEFAULT_OPTION,
                JOptionPane.WARNING_MESSAGE,null,pilihan,pilihan[0]);
            if(jawaban==0){
                db.hapusPengembalian(no);
                refreshData();
                
            }
        }
        catch (IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus!",
                "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tblHapusActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        String keyword = txtCari.getText();
        tbKembali.setModel(tabelPengembalian);
        tabelPengembalian.setData(db.cariPengembalian(keyword));
        tabelPengembalian.fireTableDataChanged();
        tbKembali.changeSelection(0, 0, false, false);
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refreshData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        Statement st = null;
        try{
            Class.forName(db.driver);
            conn = DriverManager.getConnection(db.url,db.user,db.pwd);
            
            //cetak data
            HashMap param = new HashMap();
            
            //ambil file
            File file = new File("src/report/cetakPengembalian.jasper");
            JasperReport jp = (JasperReport)JRLoader.loadObject(file);
         
            JasperPrint jasperprint = JasperFillManager.fillReport(jp, param,conn);   
            JasperViewer.viewReport(jasperprint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(JRException e){
            JOptionPane.showMessageDialog(rootPane, "Error "+e);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error "+ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error "+ex);
        }
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbKembali;
    private javax.swing.JButton tblHapus;
    private javax.swing.JButton tblTambah;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
